# Database paths 
database: 
  path: "sql/box_office.db"
  table: "movies_cleaned"

# Output paths
output:
  preprocessed_data_path: "output/data/cleaned_data/movies_preprocessed.csv"
  model_data_path: "outputs/data/modeling_data/movies_model_ready.csv"
  plots_dir: "output/modeling/eda/plots"


# Define variables
target_var: "bomb"
eda_vars: 
  numeric: ["budget",]
  categorical: ["genres","homepage","keywords"]
preprocessing:
  parse_columns:
    - genres
    - keywords
    - production_companies
    - production_countries
    - spoken_languages
  one_hot_top_n:
    genres: -1
    keywords: 50
    production_companies: 20
    production_countries: 10
    spoken_languages: 5
  categorical:
  - original_language
  numeric:
  - budget
  - runtime
  date_column: release_date